### ISSUE TITLE
Missing Data on Actual Cardinalities and Runtime in Github Repository

### ISSUE THREAD

**Issue by StCarmen** [DataManagementLab/zero-shot-cost-estimation#1]
Dear professor,

I am a reader of your recent paper about [Zero-Shot Cost Models for Out-of-the-box Learned Cost Prediction] and was intrigued to see that you have open-sourced your code on Github. In the article, you mentioned that you not only provides the runtime of the query but also the physical plan used to run the query along with actual cardinalities.

As someone who is actively working on a similar project, I am very interested in accessing this data. However, I couldn't find the corresponding exact runtime and cardinality data in your repository. I was wondering if you could kindly point me to where I might find this information or if it is possible for you to provide it?

Thank you so much for your time and help.

Best regards

**Comment by JWehrstein** [comment]
Please take a look at the data-repository at osf as mentioned in the readme.
